# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\"\x16\n\x06UserId\x12\x0c\n\x04user\x18\x01 \x01(\t\"\x18\n\x08UserName\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\x0esearchFileList\x12\x1a\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0b.searchFile\"N\n\nsearchFile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x66ile_format\x18\x03 \x01(\t\x12\x0c\n\x04\x66ile\x18\x04 \x01(\x0c\"c\n\nsearchUser\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x12\n\x05\x65mail\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_email\",\n\x0esearchUserList\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.searchUser2p\n\x0fSearcherService\x12/\n\x13getFileListByUserId\x12\x07.UserId\x1a\x0f.searchFileList\x12,\n\x0egetUsersByName\x12\t.UserName\x1a\x0f.searchUserListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERID._serialized_start=16
  _USERID._serialized_end=38
  _USERNAME._serialized_start=40
  _USERNAME._serialized_end=64
  _SEARCHFILELIST._serialized_start=66
  _SEARCHFILELIST._serialized_end=110
  _SEARCHFILE._serialized_start=112
  _SEARCHFILE._serialized_end=190
  _SEARCHUSER._serialized_start=192
  _SEARCHUSER._serialized_end=291
  _SEARCHUSERLIST._serialized_start=293
  _SEARCHUSERLIST._serialized_end=337
  _SEARCHERSERVICE._serialized_start=339
  _SEARCHERSERVICE._serialized_end=451
# @@protoc_insertion_point(module_scope)
