# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import search_pb2 as search__pb2


class SearcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getFileListByUserId = channel.unary_unary(
                '/SearcherService/getFileListByUserId',
                request_serializer=search__pb2.UserId.SerializeToString,
                response_deserializer=search__pb2.searchFileList.FromString,
                )
        self.getUsersByName = channel.unary_unary(
                '/SearcherService/getUsersByName',
                request_serializer=search__pb2.UserName.SerializeToString,
                response_deserializer=search__pb2.searchUserList.FromString,
                )


class SearcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getFileListByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUsersByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getFileListByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.getFileListByUserId,
                    request_deserializer=search__pb2.UserId.FromString,
                    response_serializer=search__pb2.searchFileList.SerializeToString,
            ),
            'getUsersByName': grpc.unary_unary_rpc_method_handler(
                    servicer.getUsersByName,
                    request_deserializer=search__pb2.UserName.FromString,
                    response_serializer=search__pb2.searchUserList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SearcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getFileListByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SearcherService/getFileListByUserId',
            search__pb2.UserId.SerializeToString,
            search__pb2.searchFileList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUsersByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SearcherService/getUsersByName',
            search__pb2.UserName.SerializeToString,
            search__pb2.searchUserList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
